name: 'octommit'
description: 'Gitops utility for updating yaml files in a github repo'
author: 'Stockopedia'
inputs:
  github-token:
    required: true
    description: 'A GitHub token that has write access to the target repository'
  script:
    required: true
    description: 'octommit script to run'
runs:
  using: 'node16'
  main: 'dist/index.js'
