name: 'Octommit'
description: 'Provide a description here'
author: 'Stockopedia'
inputs:
  github-token: # change this
    required: true
    description: "github token"
  script:
    required: true
    description: "octommit script to run"
runs:
  using: 'node12'
  main: 'dist/index.js'
