name: 'PR build'
on: 
  pull_request:

jobs:
  build: # make sure build/ci work properly
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
