name: "PR build"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
        name: Install
      - run: npm run all
        name: Compile Typescript and package
      - run: npm run test
        name: Unit tests
      - uses: ./
        name: End-to-end test
        with:
          github-token: ${{ github.token }}
          organization: Stockopedia
          repository: action-octommit
          source-branch: test
          output-branch: test
          source-path: test-file.yaml
          output-path: test-file.yaml
          set: "job:id=${{ github.run_id }};job:is_production_release=false"
          commit-message: "ci: update for job: ${{ github.run_id }}"
      - name: Verify commit
        env:
          EXPECTED_COMMIT_MESSAGE: "ci: update for job: ${{ github.run_id }}"
        run: |
          git fetch
          python validate_commit.py
      - name: comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.ARGO_GH_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Remember to upload a local build (See README)'
            })
