name: "PR build"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
        name: Install
      - run: npm run all
        name: Compile Typescript and package
      - run: npm run test
        name: Unit tests
      - uses: ./
        name: End-to-end test
        with:
          github-token: ${{ github.token }}
          organization: Stockopedia
          repository: action-octommit
          source-branch: test
          output-branch: test
          source-path: test-file.yaml
          output-path: test-file.yaml
          set: "job:id=${{ github.run_id }}"
          set-boolean: "job:is_production_release=false"
          commit-message: "ci: update for job: ${{ github.run_id }}"
      - name: Verify commit
        env:
          EXPECTED_COMMIT_MESSAGE: "ci: update for job: ${{ github.run_id }}"
        run: |
          git fetch
          python validate_commit.py
