name: Release
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all
      - uses: ./
        name: Test
        with:
          github-token: ${{ github.token }}
          organization: Stockopedia
          repository: action-octommit
          source-branch: test
          output-branch: test
          source-path: test-file.yaml
          output-path: test-file.yaml
          set: "job:id=${{ github.run_id }}"
          commit-message: "ci: update for job: ${{ github.run_id }}"
      - name: Verify commit
        run: |
          git fetch
          if [ "${git show-branch --no-name test}" = "ci: update for job: ${{ github.run_id }}" ]; then
            echo "Got matching commit message!"
            exit 0
          else
            echo "Commit message did not match!"
            exit 1
          fi
      - name: Tag release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release --branches main -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github


