name: Release
on: 
  push:
    branches:
      - main

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: Test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            octommit.update()
              .org("Stockopedia")
              .repository("action-octommit")
              .sourceBranch("branch")
              .outputBranch("branch")
              .sourcePath("test-file.yaml")
              .outputPath("test-file.yaml")
              .set("testRunDate", new Date().toString())
              .commit("[skip ci] test commit")
              .run();
      - name: Tag release
        run: npx semantic-release --branches main -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github


