name: 'test'
on: 
  push:
    branches:
      - main

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            octommit.update()
              .org("Stockopedia")
              .repository("action-octommit")
              .sourceBranch("main")
              .outputBranch("main")
              .sourcePath("test-file.yaml")
              .outputPath("test-file.yaml")
              .set("testRunDate", new Date().toString())
              .commit("[skip ci] test commit")
              .run();

